/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.helper.SendMail;
import com.models.Users;
import com.services.IUserService;
import com.services.impl.UserService;
import com.viewModel.UsersViewModel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class frm_QuenMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form frm_QuenMatKhau
     */
    
    IUserService ius;
    ArrayList lstma;
    int ran;
    
    private boolean ishidden = false;

    public frm_QuenMatKhau() {
        initComponents();
        ius = new UserService();
        lstma = new ArrayList();
        
    }

    public void addEventBackLogin(ActionListener event) {
        btnBack.addActionListener(event);
    }

    public void quenmatkhau() {
        txtUser.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        txtVerifyCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel29 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        jPanel30 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtConfirm = new javax.swing.JPasswordField();
        jPanel31 = new javax.swing.JPanel();
        txtUser9 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblHideShowP = new javax.swing.JLabel();
        lblHideShowC = new javax.swing.JLabel();
        btnSendMail = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 405));

        jPanel21.setBackground(new java.awt.Color(186, 79, 84));
        jPanel21.setPreferredSize(new java.awt.Dimension(400, 405));
        jPanel21.setLayout(null);

        jPanel25.setBackground(new java.awt.Color(186, 79, 84));
        jPanel25.setPreferredSize(new java.awt.Dimension(400, 90));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quên mật khẩu");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel6)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.add(jPanel25);
        jPanel25.setBounds(5, 5, 390, 50);

        jPanel26.setBackground(new java.awt.Color(186, 79, 84));
        jPanel26.setPreferredSize(new java.awt.Dimension(400, 160));
        jPanel26.setLayout(null);

        jPanel27.setBackground(new java.awt.Color(186, 79, 84));
        jPanel27.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel27.setLayout(new java.awt.BorderLayout(4, 4));

        txtUser.setBackground(new java.awt.Color(186, 79, 84));
        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(null);
        jPanel27.add(txtUser, java.awt.BorderLayout.PAGE_END);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tài khoản");
        jPanel27.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jPanel26.add(jPanel27);
        jPanel27.setBounds(25, 5, 250, 50);

        jPanel28.setBackground(new java.awt.Color(186, 79, 84));
        jPanel28.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel28.setLayout(new java.awt.BorderLayout(4, 4));

        txtVerifyCode.setBackground(new java.awt.Color(186, 79, 84));
        txtVerifyCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtVerifyCode.setForeground(new java.awt.Color(255, 255, 255));
        txtVerifyCode.setBorder(null);
        jPanel28.add(txtVerifyCode, java.awt.BorderLayout.PAGE_END);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mã xác thực");
        jPanel28.add(jLabel8, java.awt.BorderLayout.LINE_START);
        jPanel28.add(jSeparator3, java.awt.BorderLayout.PAGE_START);

        jPanel26.add(jPanel28);
        jPanel28.setBounds(25, 60, 250, 50);

        jPanel29.setBackground(new java.awt.Color(186, 79, 84));
        jPanel29.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel29.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mật khẩu mới");
        jPanel29.add(jLabel9, java.awt.BorderLayout.LINE_START);
        jPanel29.add(jSeparator2, java.awt.BorderLayout.PAGE_START);

        txtPass.setBackground(new java.awt.Color(186, 79, 84));
        txtPass.setBorder(null);
        jPanel29.add(txtPass, java.awt.BorderLayout.PAGE_END);

        jPanel26.add(jPanel29);
        jPanel29.setBounds(25, 115, 250, 50);

        jPanel30.setBackground(new java.awt.Color(186, 79, 84));
        jPanel30.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel30.setLayout(new java.awt.BorderLayout(4, 4));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Xác nhận mật khẩu mới");
        jPanel30.add(jLabel10, java.awt.BorderLayout.LINE_START);
        jPanel30.add(jSeparator1, java.awt.BorderLayout.PAGE_START);

        txtConfirm.setBackground(new java.awt.Color(186, 79, 84));
        txtConfirm.setBorder(null);
        jPanel30.add(txtConfirm, java.awt.BorderLayout.PAGE_END);

        jPanel26.add(jPanel30);
        jPanel30.setBounds(25, 170, 250, 50);

        jPanel31.setBackground(new java.awt.Color(186, 79, 84));
        jPanel31.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel31.setLayout(new java.awt.BorderLayout(4, 4));

        txtUser9.setBackground(new java.awt.Color(186, 79, 84));
        txtUser9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtUser9.setForeground(new java.awt.Color(255, 255, 255));
        txtUser9.setBorder(null);
        jPanel31.add(txtUser9, java.awt.BorderLayout.PAGE_END);
        jPanel31.add(jSeparator4, java.awt.BorderLayout.PAGE_START);

        jPanel26.add(jPanel31);
        jPanel31.setBounds(25, 225, 250, 50);

        lblHideShowP.setBackground(new java.awt.Color(255, 255, 255));
        lblHideShowP.setForeground(new java.awt.Color(255, 102, 102));
        lblHideShowP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/witness.png"))); // NOI18N
        lblHideShowP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHideShowPMouseClicked(evt);
            }
        });
        jPanel26.add(lblHideShowP);
        lblHideShowP.setBounds(280, 140, 24, 28);

        lblHideShowC.setBackground(new java.awt.Color(255, 255, 255));
        lblHideShowC.setForeground(new java.awt.Color(255, 102, 102));
        lblHideShowC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/witness.png"))); // NOI18N
        lblHideShowC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHideShowCMouseClicked(evt);
            }
        });
        jPanel26.add(lblHideShowC);
        lblHideShowC.setBounds(280, 200, 24, 28);

        btnSendMail.setBackground(new java.awt.Color(186, 79, 84));
        btnSendMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/email.png"))); // NOI18N
        btnSendMail.setBorder(null);
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });
        jPanel26.add(btnSendMail);
        btnSendMail.setBounds(280, 90, 30, 25);

        jPanel21.add(jPanel26);
        jPanel26.setBounds(40, 60, 320, 250);

        jButton1.setBackground(new java.awt.Color(186, 79, 84));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xác nhận");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(150, 38));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton1);
        jButton1.setBounds(150, 330, 90, 30);

        btnBack.setBackground(new java.awt.Color(186, 79, 84));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(204, 204, 255));
        btnBack.setText("Đăng nhập ->");
        btnBack.setBorder(null);
        btnBack.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel21.add(btnBack);
        btnBack.setBounds(270, 360, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblHideShowPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideShowPMouseClicked
        // TODO add your handling code here:
        ishidden = !ishidden;

        if (ishidden) {
            this.txtPass.setEchoChar((char) 0);
            this.lblHideShowP.setIcon(new ImageIcon("D:\\Da1_2024\\Shoes_Store\\src\\com\\raven\\icon\\hide.png"));
        } else {
            this.lblHideShowP.setIcon(new ImageIcon("D:\\Da1_2024\\Shoes_Store\\src\\com\\raven\\icon\\witness.png"));
            if (txtPass.getText().equals("Mật khẩu")) {
                return;
            }
            this.txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_lblHideShowPMouseClicked

    private void lblHideShowCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideShowCMouseClicked
        // TODO add your handling code here:
        ishidden = !ishidden;

        if (ishidden) {
            this.txtConfirm.setEchoChar((char) 0);
            this.lblHideShowC.setIcon(new ImageIcon("D:\\Da1_2024\\Shoes_Store\\src\\com\\raven\\icon\\hide.png"));
        } else {
            this.lblHideShowC.setIcon(new ImageIcon("D:\\Da1_2024\\Shoes_Store\\src\\com\\raven\\icon\\witness.png"));
            if (txtConfirm.getText().equals("Mật khẩu")) {
                return;
            }
            this.txtConfirm.setEchoChar('*');
        }
    }//GEN-LAST:event_lblHideShowCMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int code = 0;
        if (txtUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tài khoản!");
            return;
        }

        if (txtVerifyCode.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã bảo mật!");
            return;
        }

        try {
            code = Integer.parseInt(txtVerifyCode.getText().trim());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Mã bảo mật phải là số!");
            return;
        }

        if (txtPass.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Mời bạn nhập mật khẩu mới!");
            return;
        }

        if (txtPass.getText().length() < 6) {
            JOptionPane.showMessageDialog(this, "Độ dài mật khẩu yêu cầu 6 kí tự trở lên!");
            return;
        }

        if (txtConfirm.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Mời bạn xác nhận mật khẩu mới!");
            return;
        }
        if (!txtPass.getText().equals(txtConfirm.getText())) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới và mật khẩu xác nhận chưa giống nhau!");
            return;
        }
        if (ius.getUserbytk(txtUser.getText()) == null) {
            JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại!");
            return;
        }
        if (code == ran) {
            UsersViewModel us = new UsersViewModel();
            us.setMk(txtPass.getText());
            ius.updateMK(us, txtUser.getText());
            JOptionPane.showMessageDialog(this, "Thay đổi mật khẩu thành công");
            return;
        }
        JOptionPane.showMessageDialog(this, "Sai mã bảo mật");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        // TODO add your handling code here:
        String taikhoan = txtUser.getText().trim();

        
        Users user = ius.getUserbytk(taikhoan);
        if (user.getTk() == null) {
            JOptionPane.showMessageDialog(this, "không có tài khoản này ( " + taikhoan + " ) vui lòng nhập tài khoản khác!");
            return;
        }
        Random random = new Random();
        ran = random.nextInt(99999);
        String sub = "Verification code";
        String messsage = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title></title>\n"
                + "</head>\n"
                + "<body>\n"
                + "    <h3 style=\"color: blue;\">Verification code</h3>\n"
                + "    <div>Your verification code is : " + ran + "</div>\n"
                + "    <h3 style=\"color: blue;\">Thank you!</h3>\n"
                + "</body>\n"
                + "</html>";
        SendMail.send(user.getEmail(), sub, messsage);
        JOptionPane.showMessageDialog(this, " Mã đã gửi vào gmail : " + user.getEmail());
        txtUser.setEnabled(false);
    }//GEN-LAST:event_btnSendMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendMail;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblHideShowC;
    private javax.swing.JLabel lblHideShowP;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUser9;
    private javax.swing.JTextField txtVerifyCode;
    // End of variables declaration//GEN-END:variables
}
