/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.services.IHoaDonService;
import com.services.impl.HoaDonService;
import com.viewModel.HoaDonChiTietViewModel;
import com.viewModel.HoaDonViewModel;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Lich_su extends javax.swing.JPanel {

    /**
     * Creates new form San_Pham
     */
    private DefaultTableModel _dtmHD;
    private IHoaDonService service;

    public Lich_su() {
        initComponents();
        setOpaque(false);
        service = new HoaDonService();
        loadData();
    }

    private void loadData() {
        _dtmHD = (DefaultTableModel) tblHoaDon.getModel();
        _dtmHD.setRowCount(0);
        List<HoaDonViewModel> _listHoaDon = service.getListHoaDon();
        for (HoaDonViewModel h : _listHoaDon) {
            _dtmHD.addRow(new Object[]{
                h.getMa(),
               (h.getKh() != null) ? h.getKh().getTen() : "",
                h.getUs().getTen(),
                h.getNgayTaoAsString(),
                h.getNgayThanhToan(),
                h.getTongTien(),
                h.getTinhTrang() == 1 ? "Đã thanh toán" : "Chưa thanh toán"

            });
        }
    }

    private void TimKiemHoaDonTheoTenKH() {
        _dtmHD = (DefaultTableModel) tblHoaDon.getModel();
        _dtmHD.setRowCount(0);
        List<HoaDonViewModel> _listByTen = service.getHoaDonByTen("%" + txtSearchName.getText().trim() + "%");
        for (HoaDonViewModel h : _listByTen) {
            _dtmHD.addRow(new Object[]{
                h.getMa(),
                (h.getKh() != null) ? h.getKh().getTen() : "",
                h.getUs().getTen(),
                h.getNgayTaoAsString(),
                h.getNgayThanhToan(),
                h.getTongTien(),
                h.getTinhTrang() == 1 ? "Đã thanh toán" : "Chưa thanh toán"

            });
        }
    }

    private void TimKiemHoaDonTheoTT() {
        int trangThai = cbbTrangThai.getSelectedIndex();
        _dtmHD = (DefaultTableModel) tblHoaDon.getModel();
        _dtmHD.setRowCount(0);
        List<HoaDonViewModel> _listByTT = service.TimKiemTheoTTHoaDon(trangThai);
        for (HoaDonViewModel h : _listByTT) {
            _dtmHD.addRow(new Object[]{
                h.getMa(),
                (h.getKh() != null) ? h.getKh().getTen() : "",
                h.getUs().getTen(),
                h.getNgayTaoAsString(),
                h.getNgayThanhToan(),
                h.getTongTien(),
                h.getTinhTrang() == 1 ? "Đã thanh toán" : "Chưa thanh toán"

            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonCT = new javax.swing.JTable();
        cbbTrangThai = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtDate_NgayTT = new com.toedter.calendar.JDateChooser();
        roundPanel1 = new com.raven.swing.RoundPanel();
        txtSearchName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1124, 666));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1124, 666));
        jPanel1.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));
        jPanel8.setLayout(null);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Khách hàng", "Người tạo", "Ngày tạo", "Ngày thanh toán", "Tổng tiền", "Tình trạng"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(18, 114, 1080, 216);
        jPanel8.add(jSeparator1);
        jSeparator1.setBounds(6, 348, 1107, 10);

        tblHoaDonCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Mã Sản Phẩm", "Tên Sản Phẩm", "Số Lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tblHoaDonCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonCTMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDonCT);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(18, 365, 1080, 223);

        cbbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chưa thanh toán", "Đã thanh toán" }));
        cbbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTrangThaiActionPerformed(evt);
            }
        });
        jPanel8.add(cbbTrangThai);
        cbbTrangThai.setBounds(287, 68, 157, 28);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Trạng thái");
        jPanel8.add(jLabel19);
        jLabel19.setBounds(207, 71, 68, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Ngày thanh toán");
        jPanel8.add(jLabel20);
        jLabel20.setBounds(565, 71, 111, 20);

        txtDate_NgayTT.setDateFormatString("dd/MM/yyyy");
        txtDate_NgayTT.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtDate_NgayTTAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel8.add(txtDate_NgayTT);
        txtDate_NgayTT.setBounds(681, 68, 166, 28);

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtSearchName.setBorder(null);
        txtSearchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNameKeyReleased(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/search_24px.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap())
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearchName)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
        );

        jPanel8.add(roundPanel1);
        roundPanel1.setBounds(180, 20, 720, 30);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(12, 13, 1119, 669);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int row = tblHoaDon.getSelectedRow();
        _dtmHD = (DefaultTableModel) tblHoaDonCT.getModel();
        _dtmHD.setRowCount(0);
        List<HoaDonChiTietViewModel> _listHDCT = service.getHDCT(tblHoaDon.getValueAt(row, 0).toString());
        for (HoaDonChiTietViewModel CT : _listHDCT) {
            _dtmHD.addRow(new Object[]{
                CT.getHoaDon().getMa(),
                CT.getSanPham().getMa(),
                CT.getSanPham().getTen(),
                CT.getSoluong(),
                CT.getDonGia(),
                CT.getThanhTien()});
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void txtSearchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNameKeyReleased
        // TODO add your handling code here:
        TimKiemHoaDonTheoTenKH();
    }//GEN-LAST:event_txtSearchNameKeyReleased

    private void cbbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTrangThaiActionPerformed
        // TODO add your handling code here:
        TimKiemHoaDonTheoTT();
    }//GEN-LAST:event_cbbTrangThaiActionPerformed

    public void timTheoNgayThanhToan(){
        if (txtDate_NgayTT.getDate() != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date3 = sdf.format(txtDate_NgayTT.getDate());
            if (service.GetTimNTT(date3).isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không Có Ngày Thanh Toán Nào");
                return;
            }
            _dtmHD.setRowCount(0);
            List<HoaDonViewModel> list = service.GetTimNTT(date3);
            for (HoaDonViewModel hoaDonViewModel : list) {
                _dtmHD.addRow(new Object[]{
                    hoaDonViewModel.getMa(),
                    hoaDonViewModel.getUs().getTen(),
                    (hoaDonViewModel.getKh() != null) ? hoaDonViewModel.getKh().getTen() : "",
                    hoaDonViewModel.getTongTien(),
                    hoaDonViewModel.getNgayTao(),
                    hoaDonViewModel.getNgayThanhToan(),
                    hoaDonViewModel.getTinhTrang() == 0 ? "Chưa thanh toán" : "Đã thanh toán",
                    hoaDonViewModel.getGhiChu(),});

            }

        }
    }
    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        timTheoNgayThanhToan();
    }//GEN-LAST:event_jLabel18MouseClicked

    private void txtDate_NgayTTAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtDate_NgayTTAncestorAdded
        // TODO add your handling code here:
        timTheoNgayThanhToan();
    }//GEN-LAST:event_txtDate_NgayTTAncestorAdded

    private void tblHoaDonCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonCTMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblHoaDonCTMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbTrangThai;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private com.raven.swing.RoundPanel roundPanel1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonCT;
    private com.toedter.calendar.JDateChooser txtDate_NgayTT;
    private javax.swing.JTextField txtSearchName;
    // End of variables declaration//GEN-END:variables

}
