/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.helper.CurrencyConvert;
import com.models.ThongKe;
import com.repositories.impl.ThongKeRepository;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Thong_ke extends javax.swing.JPanel {

    private ThongKeRepository repo = new ThongKeRepository();
    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form San_Pham
     */
    public Thong_ke() {
        initComponents();
        defaultTableModel = (DefaultTableModel) tblSanPham.getModel();
        setOpaque(false);
        choDay1.setVisible(false);
        choMonth1.setVisible(false);
        choYear1.setVisible(false);
        choDateTu1.setVisible(false);
        choDateDen1.setVisible(false);
        lblTu1.setVisible(false);
        lblDen1.setVisible(false);
        loadLbl();
        loadSP(repo.getsp());
    }

    private void loadLbl() {
        lblHoaDon.setText(String.valueOf(repo.gethdday()));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtday()));
        lblSanPham.setText(String.valueOf(repo.getbyday()));
    }

    private void loadSP(List<ThongKe> _lstTK) {
        defaultTableModel.setRowCount(0);
        int stt = 1;
        for (ThongKe x : _lstTK) {
            defaultTableModel.addRow(new Object[]{
                stt,
                x.getSp(),
                x.getSoSP()
            });
            stt++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        choDay1 = new com.toedter.calendar.JDayChooser();
        cbbLoc1 = new javax.swing.JComboBox<>();
        choMonth1 = new com.toedter.calendar.JMonthChooser();
        rdoNgay1 = new javax.swing.JRadioButton();
        rdoThang1 = new javax.swing.JRadioButton();
        rdoNam1 = new javax.swing.JRadioButton();
        rdoKhoang1 = new javax.swing.JRadioButton();
        choYear1 = new com.toedter.calendar.JYearChooser();
        lblTu1 = new javax.swing.JLabel();
        choDateTu1 = new com.toedter.calendar.JMonthChooser();
        lblDen1 = new javax.swing.JLabel();
        choDateDen1 = new com.toedter.calendar.JMonthChooser();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1124, 666));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1124, 666));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Doanh thu");

        lblDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoanhThu.setForeground(new java.awt.Color(0, 204, 204));
        lblDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/money.png"))); // NOI18N
        lblDoanhThu.setText("-");
        lblDoanhThu.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Hóa đơn");

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(0, 204, 204));
        lblHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/bill.png"))); // NOI18N
        lblHoaDon.setText("-");
        lblHoaDon.setPreferredSize(new java.awt.Dimension(137, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Sản phẩm");

        lblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSanPham.setForeground(new java.awt.Color(0, 204, 204));
        lblSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/box.png"))); // NOI18N
        lblSanPham.setText("-");
        lblSanPham.setPreferredSize(new java.awt.Dimension(137, 60));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(98, 98, 98))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Tên sản phẩm", "Số lượt mua"
            }
        ));
        jScrollPane1.setViewportView(tblSanPham);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin sản phẩm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbbLoc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tháng", "Năm" }));
        cbbLoc1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoc1ItemStateChanged(evt);
            }
        });

        rdoNgay1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoNgay1);
        rdoNgay1.setText("Ngày");
        rdoNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNgay1ActionPerformed(evt);
            }
        });
        rdoNgay1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoNgay1KeyReleased(evt);
            }
        });

        rdoThang1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoThang1);
        rdoThang1.setText("Tháng");
        rdoThang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoThang1ActionPerformed(evt);
            }
        });
        rdoThang1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoThang1KeyReleased(evt);
            }
        });

        rdoNam1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoNam1);
        rdoNam1.setText("Năm");
        rdoNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNam1ActionPerformed(evt);
            }
        });
        rdoNam1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoNam1KeyReleased(evt);
            }
        });

        rdoKhoang1.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoKhoang1);
        rdoKhoang1.setText("Tìm theo khoảng");
        rdoKhoang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhoang1ActionPerformed(evt);
            }
        });
        rdoKhoang1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoKhoang1KeyReleased(evt);
            }
        });

        lblTu1.setText("Từ");

        lblDen1.setText("Đến");

        jLabel2.setText("Sắp xếp theo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(cbbLoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(248, 248, 248)
                                        .addComponent(choMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(248, 248, 248)
                                        .addComponent(choYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(lblTu1)
                                        .addGap(5, 5, 5)
                                        .addComponent(choDateTu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(lblDen1)
                                        .addGap(5, 5, 5)
                                        .addComponent(choDateDen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(choDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoThang1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoNam1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoKhoang1))))))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbLoc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(choMonth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(choYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choDateTu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(choDateDen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTu1)
                                            .addComponent(lblDen1)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdoNgay1)
                                .addGap(6, 6, 6)
                                .addComponent(rdoThang1)
                                .addGap(9, 9, 9)
                                .addComponent(rdoNam1)
                                .addGap(13, 13, 13)
                                .addComponent(rdoKhoang1))
                            .addComponent(choDay1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbLoc1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoc1ItemStateChanged
        // TODO add your handling code here:
        String TenDanhMuc = cbbLoc1.getSelectedItem().toString();
        if (TenDanhMuc.equals("Ngày")) {
            lblSanPham.setText(String.valueOf(repo.getbyday()));
            lblHoaDon.setText(String.valueOf(repo.gethdday()));
            lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtday()));

            loadSP(repo.getsp());

        } else if (TenDanhMuc.equals("Tháng")) {
            lblSanPham.setText(String.valueOf(repo.getSPbyMonth()));
            lblHoaDon.setText(String.valueOf(repo.gethdMonth()));
            lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtMonth()));

            loadSP(repo.getspByMonth());

        } else if (TenDanhMuc.equals("Năm")) {
            lblSanPham.setText(String.valueOf(repo.getSPbyYear()));
            lblHoaDon.setText(String.valueOf(repo.gethdYear()));
            lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtYear()));

            loadSP(repo.getspbyYear());
        }

    }//GEN-LAST:event_cbbLoc1ItemStateChanged

    private void rdoNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNgay1ActionPerformed
        // TODO add your handling code here:
        rdoNgay();
    }//GEN-LAST:event_rdoNgay1ActionPerformed

    private void rdoNgay1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoNgay1KeyReleased
        // TODO add your handling code here:
        rdoNgay();
    }//GEN-LAST:event_rdoNgay1KeyReleased

    private void rdoThang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoThang1ActionPerformed
        // TODO add your handling code here:
        rdoThang();
    }//GEN-LAST:event_rdoThang1ActionPerformed

    private void rdoThang1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoThang1KeyReleased
        // TODO add your handling code here:
        rdoThang();

    }//GEN-LAST:event_rdoThang1KeyReleased

    private void rdoNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNam1ActionPerformed
        // TODO add your handling code here:
        rdoNam();
    }//GEN-LAST:event_rdoNam1ActionPerformed

    private void rdoNam1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoNam1KeyReleased
        // TODO add your handling code here:
        rdoNam();
    }//GEN-LAST:event_rdoNam1KeyReleased

    private void rdoKhoang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhoang1ActionPerformed
        // TODO add your handling code here:
        rdoKhoang();
    }//GEN-LAST:event_rdoKhoang1ActionPerformed

    private void rdoKhoang1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoKhoang1KeyReleased
        // TODO add your handling code here:
        rdoKhoang();
    }//GEN-LAST:event_rdoKhoang1KeyReleased

    private void rdoNgay() {
        choDay1.setVisible(true);
        choMonth1.setVisible(false);
        choYear1.setVisible(false);
        choDateTu1.setVisible(false);
        choDateDen1.setVisible(false);
        lblTu1.setVisible(false);
        lblDen1.setVisible(false);
        lblHoaDon.setText(String.valueOf(repo.gethdday(String.valueOf(choDay1.getDay()))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtday(String.valueOf(choDay1.getDay()))));
        lblSanPham.setText(String.valueOf(repo.getbyday(String.valueOf(choDay1.getDay()))));
        loadSP(repo.getspday(String.valueOf(choDay1.getDay())));
    }

    private void rdoThang() {
        choDay1.setVisible(false);
        choMonth1.setVisible(true);
        choYear1.setVisible(false);
        choDateTu1.setVisible(false);
        choDateDen1.setVisible(false);
        lblTu1.setVisible(false);
        lblDen1.setVisible(false);
        lblHoaDon.setText(String.valueOf(repo.gethdmonth(String.valueOf(choMonth1.getMonth()))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtmonth(String.valueOf(choMonth1.getMonth()))));
        lblSanPham.setText(String.valueOf(repo.getbymonth(String.valueOf(choMonth1.getMonth()))));
        loadSP(repo.getspmonth(String.valueOf(choMonth1.getMonth())));
    }

    private void rdoNam() {
        choDay1.setVisible(false);
        choMonth1.setVisible(false);
        choYear1.setVisible(true);
        choDateTu1.setVisible(false);
        choDateDen1.setVisible(false);
        lblTu1.setVisible(false);
        lblDen1.setVisible(false);
        lblHoaDon.setText(String.valueOf(repo.gethdyear(String.valueOf(choYear1.getYear()))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtyear(String.valueOf(choYear1.getYear()))));
        lblSanPham.setText(String.valueOf(repo.getbyyear(String.valueOf(choYear1.getYear()))));
        loadSP(repo.getspyear(String.valueOf(choYear1.getYear())));
    }

    private void rdoKhoang() {
        choDay1.setVisible(false);
        choMonth1.setVisible(false);
        choYear1.setVisible(false);
        choDateTu1.setVisible(true);
        choDateDen1.setVisible(true);
        lblTu1.setVisible(true);
        lblDen1.setVisible(true);
        if (choDateTu1.getMonth() + 1 > choDateDen1.getMonth() + 1) {
            JOptionPane.showMessageDialog(this, "Tháng bắt đầu phải nhỏ hơn tháng kết thúc");
            return;
        }

        lblHoaDon.setText(String.valueOf(repo.gethdkhoang1(String.valueOf(choDateTu1.getMonth() + 1), String.valueOf(choDateDen1.getMonth() + 1))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtkhoang1(String.valueOf(choDateTu1.getMonth() + 1), String.valueOf(choDateDen1.getMonth() + 1))));
        lblSanPham.setText(String.valueOf(repo.getbykhoang1(String.valueOf(choDateTu1.getMonth() + 1), String.valueOf(choDateDen1.getMonth() + 1))));
        loadSP(repo.getspkhoang(String.valueOf(choDateTu1.getMonth() + 1), String.valueOf(choDateDen1.getMonth() + 1)));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLoc1;
    private com.toedter.calendar.JMonthChooser choDateDen1;
    private com.toedter.calendar.JMonthChooser choDateTu1;
    private com.toedter.calendar.JDayChooser choDay1;
    private com.toedter.calendar.JMonthChooser choMonth1;
    private com.toedter.calendar.JYearChooser choYear1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDen1;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblTu1;
    private javax.swing.JRadioButton rdoKhoang1;
    private javax.swing.JRadioButton rdoNam1;
    private javax.swing.JRadioButton rdoNgay1;
    private javax.swing.JRadioButton rdoThang1;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables

}
