/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.helper.CurrencyConvert;
import com.models.ThongKe;
import com.repositories.impl.ThongKeRepository;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Thong_ke extends javax.swing.JPanel {

    private ThongKeRepository repo = new ThongKeRepository();
    private DefaultTableModel defaultTableModel;

    /**
     * Creates new form San_Pham
     */
    public Thong_ke() {
        initComponents();
        defaultTableModel = (DefaultTableModel) tblSanPham.getModel();
        setOpaque(false);
        choDay.setVisible(false);
        choMonth.setVisible(false);
        choYear.setVisible(false);
        choDateTu.setVisible(false);
        choDateDen.setVisible(false);
        lblTu.setVisible(false);
        lblDen.setVisible(false);
        loadLbl();
        loadSP(repo.getsp());
    }

    private void loadLbl() {
        lblHoaDon.setText(String.valueOf(repo.gethdday()));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtday()));
        lblSanPham.setText(String.valueOf(repo.getbyday()));
    }

    private void loadSP(List<ThongKe> _lstTK) {
        defaultTableModel.setRowCount(0);
        int stt = 1;
        for (ThongKe x : _lstTK) {
            defaultTableModel.addRow(new Object[]{
                stt,
                x.getChiTietSP(),
                x.getSoSP()
            });
            stt++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblSanPham = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        choDay = new com.toedter.calendar.JDayChooser();
        cbbLoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        choMonth = new com.toedter.calendar.JMonthChooser();
        rdoNgay = new javax.swing.JRadioButton();
        rdoThang = new javax.swing.JRadioButton();
        rdoNam = new javax.swing.JRadioButton();
        rdoKhoang = new javax.swing.JRadioButton();
        choYear = new com.toedter.calendar.JYearChooser();
        lblTu = new javax.swing.JLabel();
        choDateTu = new com.toedter.calendar.JMonthChooser();
        lblDen = new javax.swing.JLabel();
        choDateDen = new com.toedter.calendar.JMonthChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1124, 666));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1124, 666));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Doanh thu");

        lblDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDoanhThu.setForeground(new java.awt.Color(0, 204, 204));
        lblDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/money.png"))); // NOI18N
        lblDoanhThu.setText("-");
        lblDoanhThu.setPreferredSize(new java.awt.Dimension(50, 60));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Hóa đơn");

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(0, 204, 204));
        lblHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/bill.png"))); // NOI18N
        lblHoaDon.setText("-");
        lblHoaDon.setPreferredSize(new java.awt.Dimension(137, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Sản phẩm");

        lblSanPham.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSanPham.setForeground(new java.awt.Color(0, 204, 204));
        lblSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/box.png"))); // NOI18N
        lblSanPham.setText("-");
        lblSanPham.setPreferredSize(new java.awt.Dimension(137, 60));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(98, 98, 98))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);
        jPanel2.add(choDay);
        choDay.setBounds(550, 0, 340, 130);

        cbbLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày", "Tháng", "Năm" }));
        cbbLoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLocItemStateChanged(evt);
            }
        });
        jPanel2.add(cbbLoc);
        cbbLoc.setBounds(120, 50, 110, 22);

        jLabel2.setText("Sắp xếp theo");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(42, 54, 68, 16);
        jPanel2.add(choMonth);
        choMonth.setBounds(798, 34, 95, 22);

        rdoNgay.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoNgay);
        rdoNgay.setText("Ngày");
        rdoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNgayActionPerformed(evt);
            }
        });
        rdoNgay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoNgayKeyReleased(evt);
            }
        });
        jPanel2.add(rdoNgay);
        rdoNgay.setBounds(901, 0, 115, 25);

        rdoThang.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoThang);
        rdoThang.setText("Tháng");
        rdoThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoThangActionPerformed(evt);
            }
        });
        rdoThang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoThangKeyReleased(evt);
            }
        });
        jPanel2.add(rdoThang);
        rdoThang.setBounds(901, 31, 115, 25);

        rdoNam.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoNam);
        rdoNam.setText("Năm");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });
        rdoNam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoNamKeyReleased(evt);
            }
        });
        jPanel2.add(rdoNam);
        rdoNam.setBounds(901, 65, 115, 25);

        rdoKhoang.setBackground(new java.awt.Color(204, 204, 255));
        buttonGroup1.add(rdoKhoang);
        rdoKhoang.setText("Tìm theo khoảng");
        rdoKhoang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhoangActionPerformed(evt);
            }
        });
        rdoKhoang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rdoKhoangKeyReleased(evt);
            }
        });
        jPanel2.add(rdoKhoang);
        rdoKhoang.setBounds(901, 103, 115, 25);
        jPanel2.add(choYear);
        choYear.setBounds(798, 68, 95, 22);

        lblTu.setText("Từ");
        jPanel2.add(lblTu);
        lblTu.setBounds(654, 107, 13, 16);
        jPanel2.add(choDateTu);
        choDateTu.setBounds(672, 103, 95, 22);

        lblDen.setText("Đến");
        jPanel2.add(lblDen);
        lblDen.setBounds(772, 107, 21, 16);
        jPanel2.add(choDateDen);
        choDateDen.setBounds(798, 103, 95, 22);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Tên sản phẩm", "Số lượt mua"
            }
        ));
        jScrollPane1.setViewportView(tblSanPham);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thông tin sản phẩm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(418, 418, 418)
                .addComponent(jLabel1)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbLocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLocItemStateChanged
        // TODO add your handling code here:
        String TenDanhMuc = cbbLoc.getSelectedItem().toString();
        if (TenDanhMuc.equals("Ngày")) {
            lblSanPham.setText(String.valueOf(repo.getbyday()));
            lblHoaDon.setText(String.valueOf(repo.gethdday()));
            lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtday()));

            loadSP(repo.getsp());

        } else if (TenDanhMuc.equals("Tháng")) {
            lblSanPham.setText(String.valueOf(repo.getSPbyMonth()));
            lblHoaDon.setText(String.valueOf(repo.gethdMonth()));
            lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtMonth()));

            loadSP(repo.getspByMonth());

        } else if (TenDanhMuc.equals("Năm")) {
            lblSanPham.setText(String.valueOf(repo.getSPbyYear()));
            lblHoaDon.setText(String.valueOf(repo.gethdYear()));
            lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtYear()));

            loadSP(repo.getspbyYear());

        }
    }//GEN-LAST:event_cbbLocItemStateChanged

    private void rdoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNgayActionPerformed
        // TODO add your handling code here:
        rdoNgay();
    }//GEN-LAST:event_rdoNgayActionPerformed

    private void rdoThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoThangActionPerformed
        // TODO add your handling code here:
        rdoThang();
    }//GEN-LAST:event_rdoThangActionPerformed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
        rdoNam();
    }//GEN-LAST:event_rdoNamActionPerformed

    private void rdoKhoangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhoangActionPerformed
        // TODO add your handling code here:
        rdoKhoang();
    }//GEN-LAST:event_rdoKhoangActionPerformed

    private void rdoNgay(){
        choDay.setVisible(true);
        choMonth.setVisible(false);
        choYear.setVisible(false);
        choDateTu.setVisible(false);
        choDateDen.setVisible(false);
        lblTu.setVisible(false);
        lblDen.setVisible(false);
        lblHoaDon.setText(String.valueOf(repo.gethdday(String.valueOf(choDay.getDay()))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtday(String.valueOf(choDay.getDay()))));
        lblSanPham.setText(String.valueOf(repo.getbyday(String.valueOf(choDay.getDay()))));
        loadSP(repo.getspday(String.valueOf(choDay.getDay())));
    }
    
    private void rdoNgayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoNgayKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rdoNgay();
        }
    }//GEN-LAST:event_rdoNgayKeyReleased

    private void rdoThang(){
        choDay.setVisible(false);
        choMonth.setVisible(true);
        choYear.setVisible(false);
        choDateTu.setVisible(false);
        choDateDen.setVisible(false);
        lblTu.setVisible(false);
        lblDen.setVisible(false);
        lblHoaDon.setText(String.valueOf(repo.gethdmonth(String.valueOf(choMonth.getMonth()))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtmonth(String.valueOf(choMonth.getMonth()))));
        lblSanPham.setText(String.valueOf(repo.getbymonth(String.valueOf(choMonth.getMonth()))));
        loadSP(repo.getspmonth(String.valueOf(choMonth.getMonth())));
    }
    private void rdoThangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoThangKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rdoThang();
        }
    }//GEN-LAST:event_rdoThangKeyReleased

    private void rdoNam(){
        choDay.setVisible(false);
        choMonth.setVisible(false);
        choYear.setVisible(true);
        choDateTu.setVisible(false);
        choDateDen.setVisible(false);
        lblTu.setVisible(false);
        lblDen.setVisible(false);
        lblHoaDon.setText(String.valueOf(repo.gethdyear(String.valueOf(choYear.getYear()))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtyear(String.valueOf(choYear.getYear()))));
        lblSanPham.setText(String.valueOf(repo.getbyyear(String.valueOf(choYear.getYear()))));
        loadSP(repo.getspyear(String.valueOf(choYear.getYear())));
    }
    private void rdoNamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoNamKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rdoNam();
        }
    }//GEN-LAST:event_rdoNamKeyReleased

    private void rdoKhoang(){
        choDay.setVisible(false);
        choMonth.setVisible(false);
        choYear.setVisible(false);
        choDateTu.setVisible(true);
        choDateDen.setVisible(true);
        lblTu.setVisible(true);
        lblDen.setVisible(true);
        if (choDateTu.getMonth() + 1 > choDateDen.getMonth() + 1) {
            JOptionPane.showMessageDialog(this, "Tháng bắt đầu phải nhỏ hơn tháng kết thúc");
            return;
        }
        
        lblHoaDon.setText(String.valueOf(repo.gethdkhoang1(String.valueOf(choDateTu.getMonth() + 1), String.valueOf(choDateDen.getMonth() + 1))));
        lblDoanhThu.setText(CurrencyConvert.formatCurrency(repo.getdtkhoang1(String.valueOf(choDateTu.getMonth() + 1), String.valueOf(choDateDen.getMonth() + 1))));
        lblSanPham.setText(String.valueOf(repo.getbykhoang1(String.valueOf(choDateTu.getMonth() + 1), String.valueOf(choDateDen.getMonth() + 1))));
        loadSP(repo.getspkhoang(String.valueOf(choDateTu.getMonth() + 1), String.valueOf(choDateDen.getMonth() + 1)));
    }
    
    private void rdoKhoangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rdoKhoangKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            rdoKhoang();
        }
    }//GEN-LAST:event_rdoKhoangKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLoc;
    private com.toedter.calendar.JMonthChooser choDateDen;
    private com.toedter.calendar.JMonthChooser choDateTu;
    private com.toedter.calendar.JDayChooser choDay;
    private com.toedter.calendar.JMonthChooser choMonth;
    private com.toedter.calendar.JYearChooser choYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDen;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblSanPham;
    private javax.swing.JLabel lblTu;
    private javax.swing.JRadioButton rdoKhoang;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNgay;
    private javax.swing.JRadioButton rdoThang;
    private javax.swing.JTable tblSanPham;
    // End of variables declaration//GEN-END:variables

}
